# Configuration MongoDB pour Heroku

doctrine_mongodb:
    auto_generate_proxy_classes: false
    auto_generate_hydrator_classes: false
    connections:
        default:
            server: '%env(MONGODB_URL)%'
            options: {}
    default_database: innergarden
    document_managers:
        default:
            auto_mapping: true
            mappings:
                App:
                    is_bundle: false
                    type: attribute   
                    dir: '%kernel.project_dir%/src/Document'
                    prefix: 'App\Document'
                    alias: App
