# Configuration MongoDB pour Heroku
# Désactiver temporairement MongoDB pendant le build

doctrine_mongodb:
    auto_generate_proxy_classes: false
    auto_generate_hydrator_classes: false
    connections:
        default:
            server: '%env(MONGODB_URL)%'
            options:
                connect: false  # Ne pas se connecter automatiquement
    default_database: innergarden
    document_managers:
        default:
            auto_mapping: true
            mappings:
                App:
                    is_bundle: false
                    type: annotation
                    dir: '%kernel.project_dir%/src/Document'
                    prefix: 'App\Document'
                    alias: App
